version: '3.8'

services:
  whatsapp-client:
    build: .
    volumes:
      - .:/usr/src/app
      - ./wwebjs_auth:/usr/src/app/wwebjs_auth # Persist WhatsApp session data
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/whatsapp # If you need MongoDB connection
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
